version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pagila_final
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pagila
    ports:
      - "5555:5432"
    volumes:
      - ./pagila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./pagila-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: